module.exports = {

  getAllUsers: (req, res) => {
    const db = req.app.get('db');
    // console.log('db', db);
    db.get_all_users()
      .then(
        (users) => {
          let user = users[0];
          user.addresses = JSON.parse(user.addresses);
          // console.log(user.address);
          res.status(200).send(user) 
        }
      )
      .catch(
        (err) => {
          console.log('it errored')
          res.status(500).send(err);
        }
      )
  },
  addUsers: (req,res) => {
    let people = [ { firstName: 'julio',
    lastName: 'carlson',
    email: 'julio.carlson@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/20.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"239 stevens creek blvd","city":"savannah","state":"mississippi","lat":"30.2029","long":"-118.8597"}]' },
  { firstName: 'carolyn',
    lastName: 'mason',
    email: 'carolyn.mason@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/43.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"5808 valwood pkwy","city":"killeen","state":"north dakota","lat":"84.0539","long":"117.8750"}]' },
  { firstName: 'evelyn',
    lastName: 'mckinney',
    email: 'evelyn.mckinney@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/62.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"1545 oak ridge ln","city":"gilbert","state":"illinois","lat":"32.8269","long":"65.3838"}]' },
  { firstName: 'marjorie',
    lastName: 'robinson',
    email: 'marjorie.robinson@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/30.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"3286 w gray st","city":"hialeah","state":"kentucky","lat":"52.6473","long":"-21.7960"}]' },
  { firstName: 'kenneth',
    lastName: 'neal',
    email: 'kenneth.neal@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/28.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"2112 lone wolf trail","city":"pasadena","state":"missouri","lat":"55.8119","long":"48.6405"}]' },
  { firstName: 'colleen',
    lastName: 'lucas',
    email: 'colleen.lucas@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/39.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"4819 railroad st","city":"amarillo","state":"new mexico","lat":"24.0987","long":"55.5344"}]' },
  { firstName: 'taylor',
    lastName: 'chapman',
    email: 'taylor.chapman@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/67.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"7953 lovers ln","city":"boulder","state":"new mexico","lat":"-67.5140","long":"-61.0668"}]' },
  { firstName: 'hunter',
    lastName: 'kelley',
    email: 'hunter.kelley@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/17.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"5243 mcgowen st","city":"shreveport","state":"louisiana","lat":"-6.2169","long":"1.6445"}]' },
  { firstName: 'isaiah',
    lastName: 'ellis',
    email: 'isaiah.ellis@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/23.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"6416 dane st","city":"centennial","state":"new york","lat":"34.0361","long":"-12.6421"}]' },
  { firstName: 'shelly',
    lastName: 'morgan',
    email: 'shelly.morgan@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/84.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"8495 depaul dr","city":"charlotte","state":"virginia","lat":"-48.8956","long":"-32.8449"}]' },
  { firstName: 'joan',
    lastName: 'howell',
    email: 'joan.howell@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/61.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"7873 white oak dr","city":"frederick","state":"louisiana","lat":"74.4573","long":"-127.7554"}]' },
  { firstName: 'brayden',
    lastName: 'clark',
    email: 'brayden.clark@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/82.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"7052 hickory creek dr","city":"cincinnati","state":"west virginia","lat":"79.2417","long":"-96.4373"}]' },
  { firstName: 'minnie',
    lastName: 'carter',
    email: 'minnie.carter@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/78.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"5339 daisy dr","city":"tulsa","state":"washington","lat":"-81.1440","long":"165.3442"}]' },
  { firstName: 'lucille',
    lastName: 'vargas',
    email: 'lucille.vargas@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/6.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"737 poplar dr","city":"moscow","state":"alabama","lat":"77.0298","long":"-92.0200"}]' },
  { firstName: 'ben',
    lastName: 'kuhn',
    email: 'ben.kuhn@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/82.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"9949 harrison ct","city":"van alstyne","state":"mississippi","lat":"52.9659","long":"-38.7685"}]' },
  { firstName: 'dustin',
    lastName: 'hicks',
    email: 'dustin.hicks@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/47.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"5823 bollinger rd","city":"las vegas","state":"mississippi","lat":"0.8457","long":"25.4894"}]' },
  { firstName: 'herminia',
    lastName: 'ruiz',
    email: 'herminia.ruiz@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/10.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"8676 preston rd","city":"bozeman","state":"arizona","lat":"-61.3311","long":"81.3126"}]' },
  { firstName: 'ivan',
    lastName: 'elliott',
    email: 'ivan.elliott@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/61.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"8026 valley view ln","city":"tucson","state":"mississippi","lat":"73.6281","long":"-152.9232"}]' },
  { firstName: 'julio',
    lastName: 'arnold',
    email: 'julio.arnold@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/55.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"4564 walnut hill ln","city":"torrance","state":"iowa","lat":"-72.1223","long":"-148.6287"}]' },
  { firstName: 'dianne',
    lastName: 'fletcher',
    email: 'dianne.fletcher@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/95.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"8265 e center st","city":"fort collins","state":"maryland","lat":"-72.2718","long":"-56.5102"}]' },
  { firstName: 'dora',
    lastName: 'gardner',
    email: 'dora.gardner@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/51.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"7558 homestead rd","city":"santa clara","state":"ohio","lat":"47.2527","long":"12.1981"}]' },
  { firstName: 'scarlett',
    lastName: 'owens',
    email: 'scarlett.owens@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/22.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"1130 shady ln dr","city":"riverside","state":"south dakota","lat":"47.2373","long":"169.6751"}]' },
  { firstName: 'marian',
    lastName: 'holmes',
    email: 'marian.holmes@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/95.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"4969 e pecan st","city":"topeka","state":"michigan","lat":"-74.0239","long":"95.7201"}]' },
  { firstName: 'addison',
    lastName: 'roberts',
    email: 'addison.roberts@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/73.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"3743 spring hill rd","city":"eureka","state":"kentucky","lat":"-33.7560","long":"-112.9618"}]' },
  { firstName: 'eddie',
    lastName: 'rose',
    email: 'eddie.rose@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/72.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"7555 brown terrace","city":"nampa","state":"connecticut","lat":"-22.8510","long":"160.7183"}]' },
  { firstName: 'chad',
    lastName: 'rose',
    email: 'chad.rose@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/29.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"6816 crockett st","city":"denton","state":"maine","lat":"-82.2020","long":"-2.9481"}]' },
  { firstName: 'victor',
    lastName: 'reynolds',
    email: 'victor.reynolds@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/43.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"5650 avondale ave","city":"olathe","state":"new jersey","lat":"-63.9452","long":"-28.9427"}]' },
  { firstName: 'austin',
    lastName: 'fletcher',
    email: 'austin.fletcher@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/42.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"6953 samaritan dr","city":"birmingham","state":"kansas","lat":"-21.6816","long":"-79.2919"}]' },
  { firstName: 'sophie',
    lastName: 'craig',
    email: 'sophie.craig@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/10.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"6494 lakeshore rd","city":"warren","state":"connecticut","lat":"79.1106","long":"-42.5146"}]' },
  { firstName: 'katrina',
    lastName: 'mills',
    email: 'katrina.mills@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/87.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"96 w dallas st","city":"santa clarita","state":"indiana","lat":"-87.1430","long":"99.7254"}]' },
  { firstName: 'carlos',
    lastName: 'dean',
    email: 'carlos.dean@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/57.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"6658 woodland st","city":"los angeles","state":"ohio","lat":"-38.7747","long":"101.7358"}]' },
  { firstName: 'tracey',
    lastName: 'ramirez',
    email: 'tracey.ramirez@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/22.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"3701 hillcrest rd","city":"south bend","state":"arkansas","lat":"-70.0776","long":"52.5601"}]' },
  { firstName: 'tyler',
    lastName: 'miles',
    email: 'tyler.miles@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/37.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"5427 frances ct","city":"waterbury","state":"west virginia","lat":"-13.1577","long":"-5.2132"}]' },
  { firstName: 'amanda',
    lastName: 'diaz',
    email: 'amanda.diaz@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/16.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"4113 w gray st","city":"portland","state":"north carolina","lat":"81.7186","long":"-22.0788"}]' },
  { firstName: 'irma',
    lastName: 'armstrong',
    email: 'irma.armstrong@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/40.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"3530 elgin st","city":"lewiston","state":"maryland","lat":"-25.3901","long":"129.5652"}]' },
  { firstName: 'barry',
    lastName: 'chambers',
    email: 'barry.chambers@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/87.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"8148 first street","city":"chattanooga","state":"new jersey","lat":"56.1444","long":"8.0151"}]' },
  { firstName: 'jonathan',
    lastName: 'wright',
    email: 'jonathan.wright@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/46.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"5152 oak lawn ave","city":"belen","state":"maine","lat":"-36.0434","long":"-1.3709"}]' },
  { firstName: 'adam',
    lastName: 'wheeler',
    email: 'adam.wheeler@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/83.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"1191 eason rd","city":"surprise","state":"arkansas","lat":"-2.7427","long":"151.6920"}]' },
  { firstName: 'darlene',
    lastName: 'gibson',
    email: 'darlene.gibson@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/90.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"3989 mockingbird hill","city":"nashville","state":"hawaii","lat":"78.2636","long":"-38.9564"}]' },
  { firstName: 'rose',
    lastName: 'kelly',
    email: 'rose.kelly@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/48.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"695 lovers ln","city":"san francisco","state":"maryland","lat":"-60.2200","long":"166.4841"}]' },
  { firstName: 'jimmie',
    lastName: 'mccoy',
    email: 'jimmie.mccoy@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/43.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"5403 cherry st","city":"tampa","state":"delaware","lat":"19.9140","long":"-67.2788"}]' },
  { firstName: 'rafael',
    lastName: 'sanchez',
    email: 'rafael.sanchez@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/2.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"9338 railroad st","city":"elk grove","state":"virginia","lat":"80.6304","long":"-92.8746"}]' },
  { firstName: 'steven',
    lastName: 'carroll',
    email: 'steven.carroll@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/57.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"16 lone wolf trail","city":"san diego","state":"nebraska","lat":"-61.2506","long":"-166.9406"}]' },
  { firstName: 'jackson',
    lastName: 'harrison',
    email: 'jackson.harrison@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/97.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"3187 hamilton ave","city":"virginia beach","state":"utah","lat":"43.3103","long":"-107.8903"}]' },
  { firstName: 'doris',
    lastName: 'graves',
    email: 'doris.graves@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/25.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"3714 central st","city":"tampa","state":"nevada","lat":"-59.0384","long":"-125.1983"}]' },
  { firstName: 'todd',
    lastName: 'george',
    email: 'todd.george@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/97.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"5960 walnut hill ln","city":"fremont","state":"west virginia","lat":"-60.8658","long":"7.4024"}]' },
  { firstName: 'erik',
    lastName: 'long',
    email: 'erik.long@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/93.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"7455 country club rd","city":"thousand oaks","state":"virginia","lat":"63.1411","long":"149.1882"}]' },
  { firstName: 'herman',
    lastName: 'vasquez',
    email: 'herman.vasquez@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/59.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"264 college st","city":"eureka","state":"louisiana","lat":"21.2303","long":"-141.5871"}]' },
  { firstName: 'javier',
    lastName: 'kuhn',
    email: 'javier.kuhn@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/35.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"5477 homestead rd","city":"seattle","state":"west virginia","lat":"3.2139","long":"34.0258"}]' },
  { firstName: 'danielle',
    lastName: 'harrison',
    email: 'danielle.harrison@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/70.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"163 w sherman dr","city":"raleigh","state":"nebraska","lat":"-41.0502","long":"52.6170"}]' },
  { firstName: 'bessie',
    lastName: 'peterson',
    email: 'bessie.peterson@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/55.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"9170 westheimer rd","city":"beaumont","state":"maine","lat":"60.5307","long":"74.1007"}]' },
  { firstName: 'harvey',
    lastName: 'steeves ',
    email: 'harvey.steeves@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/9.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"754 wheeler ridge dr","city":"rochmond","state":"maine","lat":"-63.6439","long":"90.8483"}]' },
  { firstName: 'bradley',
    lastName: 'fisher',
    email: 'bradley.fisher@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/97.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"4642 green rd","city":"sioux falls","state":"maine","lat":"-48.0356","long":"69.3334"}]' },
  { firstName: 'catherine',
    lastName: 'nguyen',
    email: 'catherine.nguyen@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/89.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"6423 shady ln dr","city":"hamsburg","state":"massachusetts","lat":"15.5034","long":"-134.0624"}]' },
  { firstName: 'wilma',
    lastName: 'hale',
    email: 'wilma.hale@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/88.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"6888 plum st","city":"hialeah","state":"oregon","lat":"59.2603","long":"-143.6670"}]' },
  { firstName: 'ricky',
    lastName: 'price',
    email: 'ricky.price@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/5.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"5267 brown terrace","city":"santa clarita","state":"hawaii","lat":"-73.1014","long":"21.0820"}]' },
  { firstName: 'chad',
    lastName: 'jimenez',
    email: 'chad.jimenez@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/22.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"4046 mcgowen st","city":"baton rouge","state":"iowa","lat":"-61.0638","long":"-169.2606"}]' },
  { firstName: 'kitty',
    lastName: 'miles',
    email: 'kitty.miles@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/82.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"8288 edwards rd","city":"pomona","state":"vermont","lat":"22.6488","long":"-46.9500"}]' },
  { firstName: 'jonathan',
    lastName: 'hoffman',
    email: 'jonathan.hoffman@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/70.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"8953 poplar dr","city":"oklahoma city","state":"texas","lat":"-38.6444","long":"113.3351"}]' },
  { firstName: 'landon',
    lastName: 'barnett',
    email: 'landon.barnett@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/36.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"1981 elgin st","city":"rialto","state":"new jersey","lat":"29.6266","long":"-68.8182"}]' },
  { firstName: 'katrina',
    lastName: 'beck',
    email: 'katrina.beck@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/43.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"2802 frances ct","city":"burkburnett","state":"new hampshire","lat":"-25.4049","long":"176.7148"}]' },
  { firstName: 'sherry',
    lastName: 'long',
    email: 'sherry.long@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/26.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"8137 spring hill rd","city":"cape coral","state":"florida","lat":"-79.0089","long":"-174.5270"}]' },
  { firstName: 'laurie',
    lastName: 'burton',
    email: 'laurie.burton@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/3.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"4604 karen dr","city":"altoona","state":"maryland","lat":"-59.2725","long":"13.3968"}]' },
  { firstName: 'lily',
    lastName: 'murray',
    email: 'lily.murray@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/86.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"7132 stevens creek blvd","city":"newport news","state":"new jersey","lat":"3.5203","long":"33.9305"}]' },
  { firstName: 'craig',
    lastName: 'hunt',
    email: 'craig.hunt@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/76.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"1631 wycliff ave","city":"fremont","state":"maryland","lat":"80.4918","long":"-119.1122"}]' },
  { firstName: 'clinton',
    lastName: 'bradley',
    email: 'clinton.bradley@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/88.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"5890 hillcrest rd","city":"beaumont","state":"new jersey","lat":"-31.5947","long":"72.4335"}]' },
  { firstName: 'mark',
    lastName: 'nguyen',
    email: 'mark.nguyen@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/73.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"4019 country club rd","city":"salem","state":"arizona","lat":"46.4483","long":"130.4158"}]' },
  { firstName: 'emma',
    lastName: 'watts',
    email: 'emma.watts@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/13.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"7170 college st","city":"colorado springs","state":"massachusetts","lat":"-27.0462","long":"174.7224"}]' },
  { firstName: 'jimmie',
    lastName: 'hunt',
    email: 'jimmie.hunt@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/25.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"4541 thornridge cir","city":"colorado springs","state":"indiana","lat":"72.4708","long":"19.5342"}]' },
  { firstName: 'peggy',
    lastName: 'payne',
    email: 'peggy.payne@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/85.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"2865 country club rd","city":"boston","state":"idaho","lat":"82.1404","long":"76.0633"}]' },
  { firstName: 'roberta',
    lastName: 'lowe',
    email: 'roberta.lowe@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/63.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"977 saddle dr","city":"iowa park","state":"florida","lat":"-81.4997","long":"-125.0502"}]' },
  { firstName: 'terrence',
    lastName: 'black',
    email: 'terrence.black@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/56.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"9422 elgin st","city":"portland","state":"wyoming","lat":"-35.3661","long":"154.4623"}]' },
  { firstName: 'julio',
    lastName: 'patterson',
    email: 'julio.patterson@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/34.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"4659 green rd","city":"bozeman","state":"virginia","lat":"-52.0427","long":"-89.6673"}]' },
  { firstName: 'mabel',
    lastName: 'garcia',
    email: 'mabel.garcia@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/52.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"898 country club rd","city":"flint","state":"vermont","lat":"4.6215","long":"-103.4392"}]' },
  { firstName: 'roger',
    lastName: 'barrett',
    email: 'roger.barrett@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/26.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"1844 mockingbird hill","city":"winston–salem","state":"georgia","lat":"-42.6984","long":"-129.1897"}]' },
  { firstName: 'liam',
    lastName: 'morris',
    email: 'liam.morris@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/61.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"6780 w pecan st","city":"miami gardens","state":"tennessee","lat":"-38.4497","long":"-87.3940"}]' },
  { firstName: 'russell',
    lastName: 'beck',
    email: 'russell.beck@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/12.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"3701 green rd","city":"centennial","state":"maryland","lat":"-5.5397","long":"-67.1604"}]' },
  { firstName: 'landon',
    lastName: 'graham',
    email: 'landon.graham@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/24.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"5187 lovers ln","city":"glendale","state":"washington","lat":"-52.5787","long":"-19.5597"}]' },
  { firstName: 'logan',
    lastName: 'baker',
    email: 'logan.baker@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/77.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"9803 samaritan dr","city":"west palm beach","state":"maine","lat":"40.1184","long":"105.1578"}]' },
  { firstName: 'kristin',
    lastName: 'scott',
    email: 'kristin.scott@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/42.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"6196 brown terrace","city":"cupertino","state":"vermont","lat":"80.3434","long":"81.1365"}]' },
  { firstName: 'todd',
    lastName: 'elliott',
    email: 'todd.elliott@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/92.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"456 miller ave","city":"colorado springs","state":"south dakota","lat":"-53.5860","long":"-126.1132"}]' },
  { firstName: 'lois',
    lastName: 'shaw',
    email: 'lois.shaw@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/45.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"2644 shady ln dr","city":"killeen","state":"oregon","lat":"-50.7324","long":"19.7289"}]' },
  { firstName: 'amy',
    lastName: 'carter',
    email: 'amy.carter@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/78.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"9714 brown terrace","city":"north charleston","state":"michigan","lat":"-63.9222","long":"62.4672"}]' },
  { firstName: 'mary',
    lastName: 'boyd',
    email: 'mary.boyd@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/86.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"196 washington ave","city":"pomona","state":"pennsylvania","lat":"-42.8254","long":"63.4592"}]' },
  { firstName: 'jim',
    lastName: 'cooper',
    email: 'jim.cooper@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/40.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"7540 w pecan st","city":"moreno valley","state":"california","lat":"74.8361","long":"-59.7388"}]' },
  { firstName: 'jessie',
    lastName: 'gilbert',
    email: 'jessie.gilbert@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/0.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"8180 locust rd","city":"ventura","state":"pennsylvania","lat":"-65.0988","long":"61.7309"}]' },
  { firstName: 'freddie',
    lastName: 'duncan',
    email: 'freddie.duncan@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/1.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"9596 hickory creek dr","city":"topeka","state":"alaska","lat":"-6.4432","long":"-68.2966"}]' },
  { firstName: 'willard',
    lastName: 'stone',
    email: 'willard.stone@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/91.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"9133 w pecan st","city":"lubbock","state":"michigan","lat":"-85.2266","long":"45.5784"}]' },
  { firstName: 'danny',
    lastName: 'porter',
    email: 'danny.porter@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/76.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"4659 eason rd","city":"oakland","state":"new hampshire","lat":"85.2190","long":"164.8524"}]' },
  { firstName: 'louis',
    lastName: 'gonzales',
    email: 'louis.gonzales@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/18.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"5649 smokey ln","city":"hamsburg","state":"pennsylvania","lat":"-18.7850","long":"-144.5363"}]' },
  { firstName: 'connie',
    lastName: 'mcdonalid',
    email: 'connie.mcdonalid@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/79.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"1310 groveland terrace","city":"anchorage","state":"oregon","lat":"-88.7569","long":"-142.5290"}]' },
  { firstName: 'derrick',
    lastName: 'hale',
    email: 'derrick.hale@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/80.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"2536 walnut hill ln","city":"carrollton","state":"north carolina","lat":"-79.4411","long":"109.5839"}]' },
  { firstName: 'kenzi',
    lastName: 'torres',
    email: 'kenzi.torres@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/6.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"8820 n stelling rd","city":"lafayette","state":"ohio","lat":"9.3491","long":"-159.7070"}]' },
  { firstName: 'nellie',
    lastName: 'williamson',
    email: 'nellie.williamson@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/38.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"519 lakeview st","city":"pueblo","state":"florida","lat":"69.6082","long":"-67.7393"}]' },
  { firstName: 'donald',
    lastName: 'robinson',
    email: 'donald.robinson@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/65.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"3074 oak lawn ave","city":"hayward","state":"oklahoma","lat":"58.1680","long":"126.9758"}]' },
  { firstName: 'justin',
    lastName: 'scott',
    email: 'justin.scott@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/70.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"3298 rolling green rd","city":"high point","state":"south dakota","lat":"14.7623","long":"-152.4824"}]' },
  { firstName: 'herminia',
    lastName: 'jones',
    email: 'herminia.jones@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/38.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"4426 e sandy lake rd","city":"augusta","state":"north carolina","lat":"62.7603","long":"-93.0763"}]' },
  { firstName: 'caroline',
    lastName: 'soto',
    email: 'caroline.soto@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/89.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"6009 lone wolf trail","city":"mesquite","state":"hawaii","lat":"45.7550","long":"62.9113"}]' },
  { firstName: 'suzanne',
    lastName: 'crawford',
    email: 'suzanne.crawford@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/women/15.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"7544 harrison ct","city":"paterson","state":"maryland","lat":"4.5555","long":"119.6957"}]' },
  { firstName: 'salvador',
    lastName: 'young',
    email: 'salvador.young@example.com',
    picture: 'https://randomuser.me/api/portraits/thumb/men/71.jpg',
    hasNotification: false,
    groups: '[]',
    addresses: '[{"address":"3441 frances ct","city":"port st. lucie","state":"virginia","lat":"-38.2776","long":"-175.9243"}]' } ]

    const db = req.app.get('db');
    
    db.add_fake_user([people[0].firstName, people[0].lastName, people[0].email, people[0].picture, people[0].hasNotification, people[0].groups, people[0].addresses])
      .then(
        (res) => {
          res.status(200).send('success');
        }
      )
      .catch(
        (err) => {
          res.status(500).send(err);
        }
      )
  }
}